# Generated by Django 5.0.6 on 2024-06-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asis', models.CharField(max_length=20)),
                ('apellido_asis', models.CharField(max_length=20)),
                ('correo_asis', models.CharField(max_length=254)),
                ('fec_contra_asis', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='consulta',
            fields=[
                ('id_consulta', models.AutoField(db_column='idConsulta', primary_key=True, serialize=False)),
                ('nombre_c', models.CharField(max_length=20)),
                ('apellido_c', models.CharField(max_length=20)),
                ('numero_c', models.IntegerField()),
                ('correo_c', models.EmailField(max_length=254)),
                ('consulta_c', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('nombre_curso', models.CharField(max_length=25)),
                ('id_curso', models.AutoField(db_column='idCurso', primary_key=True, serialize=False)),
                ('curso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_img', models.CharField(max_length=70)),
                ('descripcion_img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prof', models.CharField(max_length=20)),
                ('apellido_prof', models.CharField(max_length=20)),
                ('correo_prof', models.EmailField(max_length=254)),
                ('fec_contra_prof', models.DateField()),
            ],
            options={
                'db_table': 'SitioWeb_profesor',
            },
        ),
        migrations.CreateModel(
            name='utp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_utp', models.CharField(max_length=20)),
                ('apellido_utp', models.CharField(max_length=20)),
                ('correo_utp', models.EmailField(max_length=254)),
                ('fec_contra_utp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_vid', models.CharField(max_length=100)),
                ('descripcion_vid', models.TextField()),
            ],
        ),
    ]
