# Generated by Django 5.0.3 on 2024-06-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistente',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.DeleteModel(
            name='utp',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
