# Generated by Django 5.0.6 on 2024-06-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nombre_curso', models.CharField(max_length=25)),
                ('id_curso', models.AutoField(db_column='idCurso', primary_key=True, serialize=False)),
                ('curso', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='id',
        ),
        migrations.AddField(
            model_name='profesor',
            name='rut_prof',
            field=models.IntegerField(default='12345678-9', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
