# Generated by Django 5.0.6 on 2024-06-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0002_curso_remove_profesor_id_profesor_rut_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='rut_prof',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
