# Generated by Django 5.0.6 on 2024-07-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0003_curso_consulta_apoderado_c_alter_consulta_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='estado_c',
            field=models.BooleanField(default=False),
        ),
    ]
