# Generated by Django 5.0.6 on 2024-07-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0004_consulta_estado_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='respuesta_c',
            field=models.TextField(blank=True, null=True),
        ),
    ]
