# Generated by Django 5.0.6 on 2024-07-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0005_consulta_respuesta_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='SitioWeb.curso'),
        ),
    ]
